-- v6: PureRef-style reference board
CREATE TABLE IF NOT EXISTS ref_images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  file TEXT NOT NULL,
  x REAL NOT NULL DEFAULT 40,
  y REAL NOT NULL DEFAULT 60,
  w REAL NOT NULL DEFAULT 240,
  h REAL NOT NULL DEFAULT 240,
  z INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL
);
